Documentation:
  Core Documentation:
    readme_presence:
      name: README File Present
      description: Repository has a README file in the root directory.
      essential: true
      professional: true
      elite: true
      based_on: custom_logic
    descriptive_title:
      name: Descriptive Project Title
      description: README has a clear, descriptive title near the top that accurately
        represents the project's purpose and content. The title should be concise
        yet informative, avoiding uncommon acronyms or jargon without explanation.
      essential: true
      professional: true
      elite: true
    concise_project_summary:
      name: Concise Project Summary
      description: Clear statement of project or concise project summary near top
        of README
      essential: true
      professional: true
      elite: true
    detailed_project_overview:
      name: Detailed Project Overview
      description: Clear explanation of the project that provides enough context to
        understand its functionality, approach, and value. Typically 1-2 paragraphs
        that expand on the purpose statement with more details.
      essential: true
      professional: true
      elite: true
    readme_structure:
      name: Well-Structured README
      description: Well-structured readme with clear headings and logical organization
        of information into distinct sections such as overview, installation, usage,
        etc.
      essential: true
      professional: true
      elite: true
  Repository Structure Documentation:
    project_structure_explained_basic:
      name: Basic Repo Structure Overview
      description: Explanation of at least the main directories and usage scripts
        (such as /src, /data, /models, etc.).
      essential: true
      professional: true
      elite: true
    project_structure_explained_all:
      name: Comprehensive Repo Structure Documentation
      description: Explanation of all directories in the repository.
      essential: false
      professional: true
      elite: true
      instructions: |
        A brief explanation of the purpose of the directory is enough for passing the criterion.
  Setup Documentation:
    prerequisites_declared:
      name: Prerequisites Clearly Stated
      description: Lists the necessary knowledge, hardware requirements such as GPU,
        and system compatibility information before installation. This does not include
        software dependencies (e.g., Python libraries), which are covered under Environment
        & Dependency Management.
      essential: false
      professional: true
      elite: true
      instructions: |
        The prerequisites should be listed in the README file. If one prerequisite is listed, the criterion is met.
    installation_instructions_basic:
      name: Basic Installation Guide
      description: Basic installation information (dependencies)
      essential: true
      professional: true
      elite: true
    installation_step_by_step:
      name: Detailed Installation Instructions
      description: Detailed installation instructions for repo and prerequisites
      essential: false
      professional: true
      elite: true
    environment_dependency_information:
      name: Environment & Dependency Management documentation
      description: Specifies required Python version, dependency management (e.g.,
        requirements.txt, poetry.lock, conda.yaml), and recommendations for environment
        reproducibility (e.g., Docker, Conda, virtual environments). Does not cover
        hardware requirements or system compatibility, which are listed under Prerequisites
        Clearly Stated.
      essential: false
      professional: true
      elite: true
      based_on: file_content
      aggregation: OR
      include_extensions:
        - .txt
        - .toml
        - .py
        - .lock
        - .json
        - .md
        
  Usage Documentation:
    usage_instructions_basic:
      name: Basic Usage Instructions
      description: Basic information on how to use the repo (main script and execution)
      essential: true
      professional: true
      elite: true
    usage_step_by_step:
      name: Step-by-Step Usage Guide
      description: Detailed step-by-step usage instructions (data prep, execution,
        outputs)
      essential: false
      professional: true
      elite: true
    usage_examples:
      name: Practical Code Examples
      description: Concrete, executable code examples that demonstrate key functionality
        in a clear, concise manner.
      essential: false
      professional: true
      elite: true
    testing_documentation:
      name: Testing Instructions
      description: Instructions for running tests
      essential: false
      professional: true
      elite: true
  Technical Documentation:
    data_requirements_explained:
      name: Data Requirements Specified
      description: Documentation of expected data formats and setup
      essential: false
      professional: true
      elite: true
    key_parameters_explained:
      name: Parameter Documentation
      description: Documentation of key modeling parameters and considerations
      essential: false
      professional: true
      elite: true
      based_on: file_content
      aggregation: OR
    key_config_explained:
      name: Configuration Options Explained
      description: Information on key configuration options
      essential: false
      professional: true
      elite: true
    methodology_description_provided:
      name: Methodology Documentation
      description: Basic methodology information or reference to external documentation
      essential: false
      professional: true
      elite: true
  License Identification:
    license_in_readme:
      name: License Identification
      description: README includes a clear mention of the project's license(s).
      essential: true
      professional: true
      elite: true
  Community Documentation:
    contributing_guidelines_provided:
      name: Contribution Guidelines
      description: Guidelines for project contribution
      essential: false
      professional: true
      elite: true
    changelog_documented:
      name: Change History
      description: Repository includes changelog information either in README or in
        a dedicated file (like CHANGELOG.md), documenting significant version changes.
      essential: false
      professional: false
      elite: true
    contact_info_provided:
      name: Maintainer Contact Information
      description: Clear contact information for maintainers
      essential: false
      professional: false
      elite: true
      instructions: |
        The contact information should be provided in the README file. A presence of an email address is enough for passing the criterion.
